apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: orderhub
type: Opaque
stringData:
  username: orderhub
  password: orderhub123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-catalog-secret
  namespace: orderhub
type: Opaque
stringData:
  username: orderhub
  password: orderhub123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
  namespace: orderhub
type: Opaque
stringData:
  username: orderhub
  password: orderhub123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-payment-secret
  namespace: orderhub
type: Opaque
stringData:
  username: orderhub
  password: orderhub123
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: orderhub
type: Opaque
stringData:
  value: "dGVzdFNlY3JldEtleUZvckp3dFRlc3RpbmdPcmRlckh1YlByb2plY3QyMDI2IQ=="
