apiVersion: v1
kind: Secret
metadata:
  name: orderhub-secrets
  namespace: {{ .Release.Namespace | default "orderhub" }}
type: Opaque
stringData:
  db-username: {{ .Values.postgres.username }}
  db-password: {{ .Values.postgres.password }}
  jwt-secret: {{ .Values.global.jwtSecret }}
