apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: orderhub
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/marcosdias/orderhub/catalog-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres-catalog:5432/catalog_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-catalog-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-catalog-secret
                  key: password
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4317
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
